//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_AC[]= {
XXXXXXXX,XXXXXXXX,
XXXXX___,___XXXXX,
XXXXX___,___XXXXX,
________,_____XXX,
XXXXX___,_____XXX,
XXXXX___,________,
XXXXX___,________,
XXXXX___,_____XXX,
________,_____XXX,
XXXXX___,___XXXXX,
XXXXX___,___XXXXX,
XXXXXXXX,XXXXXXXX,
};

