//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_battery_AC[]= {
XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX___XX,
XXXXX___,_______X,XXXXXXXX,X_______,
XXXXX___,_______X,XXXXXXXX,X_XXXXX_,
________,________,_XXXXXXX,X_X___X_,
XXXXX___,________,_XXXXXXX,X_X___X_,
XXXXX___,________,_____X__,X_X___X_,
XXXXX___,________,_____X__,X_X___X_,
XXXXX___,________,_XXXXXXX,X_X___X_,
________,________,_XXXXXXX,X_X___X_,
XXXXX___,_______X,XXXXXXXX,X_XXXXX_,
XXXXX___,_______X,XXXXXXXX,X_______,
XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
};

