//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_battery_no[]= {
XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
________,________,________,_______X,
_XXXXXX_,_XXXXXXX,XXXXXX__,XXXXXX_X,
_XXXXXXX,X__XXXXX,XXXX__XX,XXXXXX__,
_XXXXXXX,XXX__XXX,XX__XXXX,XXXXXX__,
_XXXXXXX,XXXXX__X,__XXXXXX,XXXXXX__,
_XXXXXXX,XXXXX__X,__XXXXXX,XXXXXX__,
_XXXXXXX,XXX__XXX,XX__XXXX,XXXXXX__,
_XXXXXXX,X__XXXXX,XXXX__XX,XXXXXX__,
_XXXXXX_,_XXXXXXX,XXXXXX__,XXXXXX_X,
________,________,________,_______X,
XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
};

