//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_battery_three[]= {
XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
________,________,________,_______X,
_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX_X,
_X______,X______X,______XX,XXXXXX__,
_X______,X______X,______XX,XXXXXX__,
_X______,X______X,______XX,XXXXXX__,
_X______,X______X,______XX,XXXXXX__,
_X______,X______X,______XX,XXXXXX__,
_X______,X______X,______XX,XXXXXX__,
_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX_X,
________,________,________,_______X,
XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
};

