//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_exhaust_pause[]= {
___XX___,
___XX___,
___XX___,
___XX___,
___XX___,
___XX___,
___XX___,
___XX___,
};

