//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_infusion_stop[]= {
X_______,________,
________,________,
________,________,
________,________,
____XXXX,XXXX____,
____XXXX,XXXX____,
____XXXX,XXXX____,
____XXXX,XXXX____,
____XXXX,XXXX____,
____XXXX,XXXX____,
____XXXX,XXXX____,
____XXXX,XXXX____,
________,________,
________,________,
________,________,
X_______,________,
};

