//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_infusion_run[]= {
X_______,________,
________,________,
________,________,
________,________,
____XXX_,________,
____XXXX,________,
____XXXX,XX______,
____XXXX,XXX_____,
____XXXX,XXX_____,
____XXXX,XX______,
____XXXX,________,
____XXX_,________,
________,________,
________,________,
________,________,
X_______,________,
};

