//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_infusion_pause[]= {
X_______,________,
________,________,
________,________,
________,________,
____XXX_,_XXX____,
____XXX_,_XXX____,
____XXX_,_XXX____,
____XXX_,_XXX____,
____XXX_,_XXX____,
____XXX_,_XXX____,
____XXX_,_XXX____,
____XXX_,_XXX____,
________,________,
________,________,
________,________,
X_______,________,
};

