//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_left_arrow[]= {
XXXXXXX_,
XXXXX___,
XXX_____,
X_______,
X_______,
XXX_____,
XXXXX___,
XXXXXXX_,
};

