//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_lock[]= {
XX____XX,
X_XXXX_X,
X_XXXX_X,
X_XXXX_X,
________,
________,
________,
________,
________,
________,
};

