//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_mute_small[]= {
_XXX__XX,X_______,
X_X____X,_X______,
XX______,XX______,
XX_X__X_,XX______,
XX______,XX______,
XX______,XX______,
XX_X__X_,XX______,
XX______,XX______,
X_______,_X______,
_XXX__XX,X_______,
};

