//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_mute[]= {
XXXX__XX,XX_XXXXX,XX_X____,
XXX____X,XXXXXXXX,XXXX____,
XX______,XXXX_XXX,_XXX____,
XX______,XXXXXXXX,XXXX____,
XX______,XXXXXX_X,XXXX____,
XX______,XXXXXX_X,XXXX____,
XX______,XXXXXXXX,XXXX____,
XX______,XXXX_XXX,_XXX____,
X_______,_XXXXXXX,XXXX____,
XXXX__XX,XX_XXXXX,XX_X____,
};

