//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_right_arrow[]= {
_XXXXXXX,
___XXXXX,
_____XXX,
_______X,
_______X,
_____XXX,
___XXXXX,
_XXXXXXX,
};

