//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_selected_pointer[]= {
XXX__XXX,
XX____XX,
X______X,
X______X,
________,
________,
________,
};

