//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_set_arrow[]= {
__XXXXXX,
__XXXXXX,
___XXXXX,
____XXXX,
_____XXX,
______XX,
_______X,
________,
________,
_______X,
______XX,
_____XXX,
____XXXX,
___XXXXX,
__XXXXXX,
__XXXXXX,
};

