//generated by generate_image.rb, donot edit it
#include "constant_byte_define.h" 
const unsigned char g_img_sound_pause[]= {
XXXXXXX_,_XXXXXXX,
X_XXXXX_,_XXXXX_X,
XX_XXXX_,_XXXX_XX,
XXX_XX__,__XX_XXX,
XXXX_X_X,X_X_XXXX,
XXXXX_XX,XX_XXXXX,
XXXX_X_X,X_X_XXXX,
XXXX_XX_,_XX_XXXX,
XXX_XXX_,_XXX_XXX,
XX_XXX_X,X_XXX_XX,
XX_XX_XX,XX_XX_XX,
X_XX_XXX,XXX_XX_X,
________,________,
XX_XXXX_,_XXXX_XX,
X_XXXX__,__XXXX_X,
XXXXXXX_,_XXXXXXX,
};

