//generated by generate_font, donot edit it
extern const Font g_font_dengxian_regular_14;
extern const Font g_font_heiti_regular_60;
extern const Font g_font_heiti_regular_88;

const static FontData g_font_data_simplified_chinese[] =
{
	{"dengxian", "regular", &g_font_dengxian_regular_14},
	{"heiti", "regular", &g_font_heiti_regular_60},
	{"heiti", "regular", &g_font_heiti_regular_88},
	{NULL, NULL, NULL},
};

const static LangFontData g_lang_font_data[] = 
{
	{kSszLangSimplifiedChinese, g_font_data_simplified_chinese},
};
