//generated by generate_image.rb, donot edit it
extern unsigned char g_img_AC[];
extern unsigned char g_img_battery_AC[];
extern unsigned char g_img_battery_empty[];
extern unsigned char g_img_battery_full[];
extern unsigned char g_img_battery_no[];
extern unsigned char g_img_battery_one[];
extern unsigned char g_img_battery_three[];
extern unsigned char g_img_battery_two[];
extern unsigned char g_img_error[];
extern unsigned char g_img_exhaust[];
extern unsigned char g_img_exhaust_pause[];
extern unsigned char g_img_exhaust_run[];
extern unsigned char g_img_flush_max_dose_selected[];
extern unsigned char g_img_flush_max_dose_unselected[];
extern unsigned char g_img_history_log[];
extern unsigned char g_img_info_select[];
extern unsigned char g_img_info_unselect[];
extern unsigned char g_img_infusion_pause[];
extern unsigned char g_img_infusion_run[];
extern unsigned char g_img_infusion_stop[];
extern unsigned char g_img_left_arrow[];
extern unsigned char g_img_lock[];
extern unsigned char g_img_logo[];
extern unsigned char g_img_mode_selected[];
extern unsigned char g_img_mode_unselected[];
extern unsigned char g_img_mute[];
extern unsigned char g_img_mute_small[];
extern unsigned char g_img_new_task[];
extern unsigned char g_img_peak_set_select[];
extern unsigned char g_img_peak_set_unselect[];
extern unsigned char g_img_right_arrow[];
extern unsigned char g_img_selected_pointer[];
extern unsigned char g_img_select_1[];
extern unsigned char g_img_select_2[];
extern unsigned char g_img_set_arrow[];
extern unsigned char g_img_sound_pause[];
extern unsigned char g_img_stop_infusion[];
extern unsigned char g_img_system_setting[];
extern unsigned char g_img_time_select[];
extern unsigned char g_img_time_unselect[];
extern unsigned char g_img_unselected_pointer[];
extern unsigned char g_img_warning[];
extern unsigned char g_img_warning_common[];

const static Image g_image_data[] =
{
	{g_img_AC, 16, 12, 2, 1},
	{g_img_battery_AC, 32, 12, 4, 1},
	{g_img_battery_empty, 32, 12, 4, 1},
	{g_img_battery_full, 32, 12, 4, 1},
	{g_img_battery_no, 32, 12, 4, 1},
	{g_img_battery_one, 32, 12, 4, 1},
	{g_img_battery_three, 32, 12, 4, 1},
	{g_img_battery_two, 32, 12, 4, 1},
	{g_img_error, 36, 36, 5, 1},
	{g_img_exhaust, 32, 46, 4, 1},
	{g_img_exhaust_pause, 8, 8, 1, 1},
	{g_img_exhaust_run, 8, 8, 1, 1},
	{g_img_flush_max_dose_selected, 40, 40, 5, 1},
	{g_img_flush_max_dose_unselected, 40, 40, 5, 1},
	{g_img_history_log, 32, 46, 4, 1},
	{g_img_info_select, 40, 40, 5, 1},
	{g_img_info_unselect, 40, 40, 5, 1},
	{g_img_infusion_pause, 16, 16, 2, 1},
	{g_img_infusion_run, 16, 16, 2, 1},
	{g_img_infusion_stop, 16, 16, 2, 1},
	{g_img_left_arrow, 8, 8, 1, 1},
	{g_img_lock, 8, 10, 1, 1},
	{g_img_logo, 129, 26, 17, 1},
	{g_img_mode_selected, 40, 40, 5, 1},
	{g_img_mode_unselected, 40, 40, 5, 1},
	{g_img_mute, 20, 10, 3, 1},
	{g_img_mute_small, 10, 10, 2, 1},
	{g_img_new_task, 32, 46, 4, 1},
	{g_img_peak_set_select, 40, 40, 5, 1},
	{g_img_peak_set_unselect, 40, 40, 5, 1},
	{g_img_right_arrow, 8, 8, 1, 1},
	{g_img_selected_pointer, 8, 7, 1, 1},
	{g_img_select_1, 160, 24, 20, 1},
	{g_img_select_2, 160, 24, 20, 1},
	{g_img_set_arrow, 8, 16, 1, 1},
	{g_img_sound_pause, 16, 16, 2, 1},
	{g_img_stop_infusion, 32, 46, 4, 1},
	{g_img_system_setting, 32, 46, 4, 1},
	{g_img_time_select, 40, 40, 5, 1},
	{g_img_time_unselect, 40, 40, 5, 1},
	{g_img_unselected_pointer, 8, 1, 1, 1},
	{g_img_warning, 36, 36, 5, 1},
	{g_img_warning_common, 36, 36, 5, 1},
};
